version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    command: mongod --wiredTigerCacheSizeGB 1.5 --bind_ip_all
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: supply-flow-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/supply-flow
      - JWT_SECRET=yourSecretKey
      - PORT=3000
      - SMS_API_KEY=${SMS_API_KEY}
      - SMS_SENDER_NUMBER=${SMS_SENDER_NUMBER}
    networks:
      - app-network

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    container_name: supply-flow-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./ssl:/etc/nginx/ssl
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 