FROM node:18 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Сборка приложения для продакшн
RUN npm run build

FROM nginx:stable-alpine

# Копируем собранное приложение из этапа сборки
COPY --from=build /app/dist/supply-flow /usr/share/nginx/html/

# Копируем nginx конфиг
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] 